name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-18.04
    defaults:
      run:
        working-directory: ./portfolio-frontend
    steps:
      - name: checkout
        uses: actions/checkout@v2.4.0
      - name: setup node env
        uses: actions/setup-node@v2.5.1
        with:
          node-version: "16"
      - name: npm install
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      # - name: test
      #   run: npm run test
      # - name: e2e tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: http://localhost:5000
      # - uses: akhileshns/heroku-deploy@v3.12.12
      #   if: ${{ github.event_name == 'push' }}
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: "pokedex-1234"
      #     heroku_email: "ipwnjianrong@gmail.com"
      #     procfile: "web: npm start"
      #     healthcheck: "https://pokedex-1234.herokuapp.com/health"
      #     checkstring: "ok"
      #     rollbackonhealthcheckfailed: true
      - name: cd to ./portfolio-frontend
        run: cd portfolio-frontend
      - name: deploy to vercel
        uses: amondnet/vercel-action@v20.0.0
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID }}
          vercel-project-id: ${{ secrets.PROJECT_ID }}
          vercel-args: "--prod"
      # - uses: actions/checkout@v2
      # - name: Bump version and push tag
      #   if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message, ' '), '#skip') }}
      #   uses: anothrNick/github-tag-action@eca2b69f9e2c24be7decccd0f15fdb1ea5906598
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     DEFAULT_BUMP: patch
